apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name | trunc 63 }}
spec:
  selector:
    app: {{ .Chart.Name | trunc 63 }}
    component: web
  ports:
    - port: {{ int .Values.servicePort }}
